version: '2'
services:
    mms-app:
        image: mms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mms-mysql:3306/mms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mms-mysql:
        extends:
            file: mysql.yml
            service: mms-mysql
